language: cpp
os: linux
dist: trusty
sudo: false
env:
  global:
  - BOOST_VERSION="1.67.0"
  - LIBRARIES="--without-icu --with-libraries=chrono,log,program_options,date_time,thread,system,filesystem,regex,test"
  - BUILD_FLAGS=""
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
matrix:
  include:
  - env: COMPILER=g++-4.9
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
  - env: COMPILER=g++-5
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
  - env: COMPILER=g++-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
  - env: COMPILER=g++-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
  - env: COMPILER=clang++-3.6
    addons:
      apt:
        packages:
        - clang-3.6
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-3.6
  - env: COMPILER=clang++-3.8
    addons:
      apt:
        packages:
        - clang-3.8
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-3.8
  - env: COMPILER=clang++-3.9
    addons:
      apt:
        packages:
        - clang-3.9
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-3.9
  - env: COMPILER=clang++-4.0
    addons:
      apt:
        packages:
        - clang-4.0
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-4.0
  - env: COMPILER=clang++-5.0
    addons:
      apt:
        packages:
        - clang-5.0
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
  - env: COMPILER=clang++-6.0
    addons:
      apt:
        packages:
        - clang-6.0
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
install:
- mkdir -p ${DEPS_DIR}
- if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
- "${CXX} --version"
- |
  if [[ "${CXX%%+*}" == "clang" ]]; then

    if   [[ "${CXX}" == "clang++-3.5" ]]; then LLVM_VERSION="3.5.2";
    elif [[ "${CXX}" == "clang++-3.6" ]]; then LLVM_VERSION="3.6.2";
    elif [[ "${CXX}" == "clang++-3.7" ]]; then LLVM_VERSION="3.7.1";
    elif [[ "${CXX}" == "clang++-3.8" ]]; then LLVM_VERSION="3.8.1";
    elif [[ "${CXX}" == "clang++-3.9" ]]; then LLVM_VERSION="3.9.1";
    elif [[ "${CXX}" == "clang++-4.0" ]]; then LLVM_VERSION="4.0.1";
    elif [[ "${CXX}" == "clang++-5.0" ]]; then LLVM_VERSION="5.0.1";
    elif [[ "${CXX}" == "clang++-6.0" ]]; then LLVM_VERSION="6.0.0";
    fi

    LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz"
    LIBCXX_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}.src.tar.xz"
    LIBCXXABI_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}.src.tar.xz"

    cd ${DEPS_DIR} && mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
    travis_retry wget -O - ${LLVM_URL} | tar --strip-components=1 -xJ -C llvm || exit 1
    travis_retry wget -O - ${LIBCXX_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxx || exit 1
    travis_retry wget -O - ${LIBCXXABI_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxxabi || exit 1

    cmake -E chdir llvm/build cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/llvm/install || exit 1
    cmake --build ${DEPS_DIR}/llvm/build/projects/libcxx --target install -- -j2
    cmake --build ${DEPS_DIR}/llvm/build/projects/libcxxabi --target install -- -j2

    export CXXFLAGS="-std=c++14 -stdlib=libc++ -nostdinc++ -isystem ${DEPS_DIR}/llvm/install/include/c++/v1"
    export LDFLAGS="-L ${DEPS_DIR}/llvm/install/lib -l c++ -l c++abi"
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/llvm/install/lib"
  fi
before_script:
- |
  BOOST_URL="https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//\./_}.tar.gz"

  # create dirs for source and install
  mkdir -p ${TRAVIS_BUILD_DIR}/boost${BOOST_VERSION} ${TRAVIS_BUILD_DIR}/boost
  travis_retry wget --no-check-certificate --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/boost${BOOST_VERSION}

  if [[ "${CXX%%+*}" == "clang" ]]; then
    export TOOLSET=clang
    echo "using clang : : $CXX : <cxxflags>-std=c++14 <cxxflags>-fvisibility=hidden <cxxflags>-fPIC <cxxflags>-stdlib=libc++ <cxxflags>-nostdinc++ <cxxflags>-I${DEPS_DIR}/llvm/install/include/c++/v1 <linkflags>-stdlib=libc++ <linkflags>-L${DEPS_DIR}/llvm/install/lib <linkflags>-lc++ <linkflags>-lc++abi ;" > ~/user-config.jam
  else
    export TOOLSET=gcc
    echo "using gcc : : $CXX : <cxxflags>-std=c++14 <cxxflags>-fvisibility=hidden <cxxflags>-fPIC ;" > ~/user-config.jam
  fi
  cmake -E chdir ${TRAVIS_BUILD_DIR}/boost${BOOST_VERSION} ./bootstrap.sh --prefix=${TRAVIS_BUILD_DIR}/boost/ --with-toolset=${TOOLSET} ${LIBRARIES}
script:
- travis_wait cmake -E chdir ${TRAVIS_BUILD_DIR}/boost${BOOST_VERSION} ./b2 toolset=${TOOLSET} -d0 threading=multi threadapi=pthread variant=release --prefix=${TRAVIS_BUILD_DIR}/boost/ install
- |
  COMP="${CXX%%+*}"
  if [[ "${COMP}" == "g" ]]; then
    COMP="gcc"
  fi
  VERSION="${CXX##*-}"
  DEPLOY_FILE="boost-${BOOST_VERSION//\./_}-${COMP}-${VERSION//\./_}.7z"
  echo $DEPLOY_FILE
  cmake -E chdir ${TRAVIS_BUILD_DIR} cmake -E tar cf ${DEPLOY_FILE} --format=7zip boost
  mkdir -p ${TRAVIS_BUILD_DIR}/deploy
  cmake -E copy ${TRAVIS_BUILD_DIR}/$DEPLOY_FILE ${TRAVIS_BUILD_DIR}/deploy
  ls ${TRAVIS_BUILD_DIR}/deploy/

deploy:
  provider: s3
  skip_cleanup: true
  local_dir: deploy
  bucket: kovri-ci
  access_key_id: AKIAIA5FW5XYQ2VNCAKA
  secret_access_key:
    secure: XZ9QC3DxlaPnNQewJxLmcX7CxVqhP33Q/MABNET7YIt/Wpe2oLjTtIFp5KWgGXBIrZ5snpTiAw5v2hA0fhaWxUW/FEI1oyE7Ps7XiF5enUxfk2U6jaGH3oQ726vDE26cMtZ6BaxKNQR0XqE973omOkPAV64MDPSTJ/uRVqhj6c3tzB4RsTBDCPf18P2Xo7kFbuBzCHP6/pRfg1/zavVMr5JzjdJsmGI7/hmv0zgB8LgyZRTimzwyiHpqNQOo+AY6f6d2vHLYV4uE0WG2R0gWbMeCbTnC+BGNRJ+HnL93Ja9Rd27ekZshuyUpYkYIl3I+nX0dkuYd7GXp00fVH00oYube9ZArcdfjtSvCJxsbW9LMeoNtwFRgJrn4Qu+6Fzf8KNQownryPYIwu0dD5E20Bl3djUZoAv8Wd19R6wIrpbPj3cOXIQGP/TruOibMz5uUWUrvqOj8qUVAYZ4pvKktQjUOkcv/Ln7S8IwbYr3EYDo7YlR0uP+HotehAtsFlXBGtn3LAZRPUJHEJtp4j/WZw1BVRufuFmcDsj0NoPpJZgEKFJoyFbT93jyMrCt+PUswY7m/f36C0eSJGrbYJue1z/CLBH5c3LkD+Nerz/2AJEXBlIhPfa/iKIUDx4zbPXQT2lUwsxULOUZeWSjd8tVBIr/r26Bg+cPGVU01+INXXks=
