language: cpp
os: linux
dist: trusty
sudo: false
env:
  global:
  - BOOST_VERSION="1.67.0"
  - LIBRARIES="--without-icu --with-libraries=chrono,log,program_options,date_time,thread,system,filesystem,regex,test"
  - BUILD_FLAGS=""
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
matrix:
  include:
  - env: COMPILER=g++-4.9
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
  - env: COMPILER=g++-5
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
  - env: COMPILER=g++-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
  - env: COMPILER=g++-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
  - env: COMPILER=clang++-3.6
    addons:
      apt:
        packages:
        - clang-3.6
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-3.6
  - env: COMPILER=clang++-3.8
    addons:
      apt:
        packages:
        - clang-3.8
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-3.8
  - env: COMPILER=clang++-3.9
    addons:
      apt:
        packages:
        - clang-3.9
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-3.9
  - env: COMPILER=clang++-4.0
    addons:
      apt:
        packages:
        - clang-4.0
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-4.0
  - env: COMPILER=clang++-5.0
    addons:
      apt:
        packages:
        - clang-5.0
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
  - env: COMPILER=clang++-6.0
    addons:
      apt:
        packages:
        - clang-6.0
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
install:
- mkdir -p ${DEPS_DIR}
- if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
- "${CXX} --version"
- |
  if [[ "${CXX%%+*}" == "clang" ]]; then

    if   [[ "${CXX}" == "clang++-3.5" ]]; then LLVM_VERSION="3.5.2";
    elif [[ "${CXX}" == "clang++-3.6" ]]; then LLVM_VERSION="3.6.2";
    elif [[ "${CXX}" == "clang++-3.7" ]]; then LLVM_VERSION="3.7.1";
    elif [[ "${CXX}" == "clang++-3.8" ]]; then LLVM_VERSION="3.8.1";
    elif [[ "${CXX}" == "clang++-3.9" ]]; then LLVM_VERSION="3.9.1";
    elif [[ "${CXX}" == "clang++-4.0" ]]; then LLVM_VERSION="4.0.1";
    elif [[ "${CXX}" == "clang++-5.0" ]]; then LLVM_VERSION="5.0.1";
    elif [[ "${CXX}" == "clang++-6.0" ]]; then LLVM_VERSION="6.0.0";
    fi

    LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz"
    LIBCXX_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}.src.tar.xz"
    LIBCXXABI_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}.src.tar.xz"

    cd ${DEPS_DIR} && mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
    travis_retry wget -O - ${LLVM_URL} | tar --strip-components=1 -xJ -C llvm || exit 1
    travis_retry wget -O - ${LIBCXX_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxx || exit 1
    travis_retry wget -O - ${LIBCXXABI_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxxabi || exit 1

    cmake -E chdir llvm/build cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/llvm/install || exit 1
    cmake --build ${DEPS_DIR}/llvm/build/projects/libcxx --target install -- -j2
    cmake --build ${DEPS_DIR}/llvm/build/projects/libcxxabi --target install -- -j2

    export CXXFLAGS="-std=c++14 -stdlib=libc++ -nostdinc++ -isystem ${DEPS_DIR}/llvm/install/include/c++/v1"
    export LDFLAGS="-L ${DEPS_DIR}/llvm/install/lib -l c++ -l c++abi"
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/llvm/install/lib"
  fi
before_script:
- |
  BOOST_URL="https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//\./_}.tar.gz"

  # create dirs for source and install
  mkdir -p ${TRAVIS_BUILD_DIR}/boost${BOOST_VERSION} ${TRAVIS_BUILD_DIR}/boost
  travis_retry wget --no-check-certificate --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/boost${BOOST_VERSION}

  if [[ "${CXX%%+*}" == "clang" ]]; then
    export TOOLSET=clang
    echo "using clang : : $CXX : <cxxflags>-std=c++14 <cxxflags>-fvisibility=hidden <cxxflags>-fPIC <cxxflags>-stdlib=libc++ <cxxflags>-nostdinc++ <cxxflags>-I${DEPS_DIR}/llvm/install/include/c++/v1 <linkflags>-stdlib=libc++ <linkflags>-L${DEPS_DIR}/llvm/install/lib <linkflags>-lc++ <linkflags>-lc++abi ;" > ~/user-config.jam
  else
    export TOOLSET=gcc
    echo "using gcc : : $CXX : <cxxflags>-std=c++14 <cxxflags>-fvisibility=hidden <cxxflags>-fPIC ;" > ~/user-config.jam
  fi
  cmake -E chdir ${TRAVIS_BUILD_DIR}/boost${BOOST_VERSION} ./bootstrap.sh --prefix=${TRAVIS_BUILD_DIR}/boost/ --with-toolset=${TOOLSET} ${LIBRARIES}
script:
- cmake -E chdir ${TRAVIS_BUILD_DIR}/boost${BOOST_VERSION} ./b2 toolset=${TOOLSET} threading=multi threadapi=pthread variant=release --prefix=${TRAVIS_BUILD_DIR}/boost/ install
- |
  COMP="${CXX%%+*}"
  if [[ "${comp}" == "g" ]]; then
    COMP="gcc"
  fi
  VERSION="${COMPILER##*+}"
  DEPLOY_FILE="boost-${BOOST_VERSION//\./_}-${COMP}-${VERSION}.7z"
  echo $DEPLOY_FILE
  cmake -E chdir ${TRAVIS_BUILD_DIR} cmake -E tar cf ${DEPLOY_FILE} --format=7zip boost
  mkdir -p ${TRAVIS_BUILD_DIR}/deploy
  cmake -E copy ${TRAVIS_BUILD_DIR}/$DEPLOY_FILE ${TRAVIS_BUILD_DIR}/deploy

deploy:
  provider: releases
  api_key:
    secure: tjF4f7tJur9iPlgc4NMF9+3gcujhAg4NSV+iJRWJgBXZKYHbsLSAQo0Ejmt1GgeNvzmVhLqPkM9d/xvu8j7nkwkFjrLhlXpVvwV4u7xmON6lqiUwABHg5E+UfNPp74D0Cj8hmuzwIe61141kM0APWiYxhKyRoR7VVI0u5PeEDVpmsq530qJWz5eLGgThDj72vurP9QgKmrcS8icY0IS43FqR4Bc/khLm0fbLj0VMa+ynwGkucvi2e77zNnW7Hdy2loB60ZjLc1zCFgaotJy1c6rXPSacdvxfI65hMtQzSj1CUd2LbeE7MKZKFxjS6adt7kii9Dz1DRGTGpJDTU7Jeb2v7705pRwJi4aRnkj8sCeVUZEy1FCw24vQz1r0mE0OYP6Zm5UcvkG00egCYFdqBJ6ah2wWe0WPIRpZV+3QsCJExIr6Ioomw9z3UR2Q+4Y+c/TX9b3QmWosn4bL53qIeC7wKL0Qh2Xq5g8gB+FxCtpaRDWYP1vhm5OTPucoGDKjHDvE8FPs1bs7yd4Cf8MzbRKamEoolgz4HLRhAAVic5PFdzsKmdk4EIY8vKrTeA9FlQ6LMOXNjzdt0A9rLtBBlSIVSBUeY3bkRd2/78QviG0g53oiBE9t+d5lZ6x7fJ47E5Oi61xoHvMwxWbUZpsSXsfH772dYvM1zMwQm6YZiKQ=
  file_glob: true
  file: deploy/**
  skip_cleanup: true
  on:
    tags: true
